name: Amend PR description Roctogen

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Default

    # if: >
    #   github.event.issue.pull_request.head.repo.full_name == github.repository &&
    #   contains(github.event.issue.pull_request.labels.*.name, 'automation') &&
    #   github.actor == 'greptile[bot]' &&
    #   github.event.issue.pull_request.user.login == 'github-actions[bot]'

    steps:
      - name: Debug
        run: |
          echo "${{ github.event.issue.pull_request.head.repo.full_name }}"
          echo "${{ github.event.issue.pull_request.labels.*.name }}"
          echo "${{ github.actor }}"
          echo "${{ github.event.issue.pull_request.user.login }}"
      - name: Amend PR descriptin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.issue.pull_request.number }} --body "${{ github.event.comment.body }}"
          gh pr edit ${{ github.event.issue.pull_request.number }} --add-label "greptile"
