name: Amend PR description Roctogen

on:
  pull_request_review:
    types:
      - submitted

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'automation') &&
      github.event.review.user.login == 'greptile-apps[bot]' &&
      github.event.pull_request.user.login == 'github-actions[bot]'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Amend PR description
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          jq -r '.review.body' "$GITHUB_EVENT_PATH" > issue_description.txt
          gh pr edit ${{ github.event.pull_request.number }} --body-file issue_description.txt
          gh pr edit ${{ github.event.pull_request.number }} --add-label "greptile"
