name: Amend PR description Roctogen

on:
  pull_request_review:
    types:
      - submitted

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'automation') &&
      github.event.review.user.login == 'greptile-apps[bot]' &&
      github.event.pull_request.user.login == 'github-actions[bot]'

    steps:
      - name: Amend PR description
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ESCAPED_BODY=$(echo "{{ github.event.review.body }}" | jq -sRr @sh)
          echo gh pr edit ${{ github.event.pull_request.number }} --body "$ESCAPED_BODY"
          # gh pr edit ${{ github.event.pull_request.number }} --add-label "greptile"
