name: Update OpenAPI

on:
  workflow_dispatch:

jobs:
  update-models:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: git checkout -b "automation/update-models-${{ env.DATE }}"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: mvn -D org.slf4j.simpleLogger.defaultLogLevel=warn clean compiler:compile generate-resources
      - name: Determine new version number
        id: version-number
        run: |
          CURRENT_VERSION=$(head roctogen/Cargo.toml | grep ^version | awk '{ print $3 }' | tr -d '"')
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          ((minor++))
          patch=0
          sed -i "s/^version = \"$CURRENT_VERSION\"$/version = \"$major.$minor.$patch\"/" roctogen/Cargo.toml
          echo "VERSION=$major.$minor.$patch" >> $GITHUB_ENV
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git diff
          git add .
          git commit -m "feat: Update models and endpoints for ${{ env.DATE }}"
          git push -u origin "automation/update-models-${{ env.DATE }}" --force-with-lease
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install release-plz
        run: cargo install --locked release-plz
      - name: Run release-plz
        run: release-plz release-pr -p roctogen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

